title: JA5MlN 
author: fast learner
email: find me on github
description: > # this means to ignore newlines until "baseurl:"
  I'm so happy that you are here. Aspiring coder with communication chops and a pretty good eye for design. Could be all my dreams come true if I can just learn to git commit.

# social link
github_username:  JA5MlN

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
